### ISSUE TITLE
Migrate CDSAPI over to JuliaClimate?

### ISSUE THREAD

**Issue by juliohm** [JuliaClimate/meta#11]
I am mentoring a MLH student who is writing a package to access the https://cds.climate.copernicus.eu
database. Would you be interested in migrating the work to this organization?

https://github.com/michiboo/CDSAPI.jl

cc: @michiboo

**Comment by Balinus** [comment]
Hi juliohm!

Yes, I think that would be a good addition to the organization.

Thanks!

**Comment by Balinus** [comment]
I'm not sure you'll be able to officially register the package with such an acronym though.

**Comment by juliohm** [comment]
We had other packages with acronyms like this like GDAL, and recently GRIB. I think it is natural in this case to pursue CDSAPI, it makes a natural transition from Python.

**Comment by Balinus** [comment]
Yes, perhaps! :)

**Comment by natgeo-wong** [comment]
This would make a GREAT addition/feature to ClimateERA.jl, if he is interested!

Right now I'm just generating the python script for download.  But this seems to be a way to download the data directly using Julia which makes me happy @juliohm @michiboo if you guys are interested

**Comment by juliohm** [comment]
ClimateERA.jl could use CDSAPI.jl as a dependency to load the ERA dataset.
👍However I feel that a standalone package for CDS is needed that is
dataset agnostic.

**Comment by michiboo** [comment]
@Balinus  @natgeo-wong  Hi I try to transfer the ownership to JuliaClimate but with no success due to no permission, can you guys look into it?

**Comment by Balinus** [comment]
I haven't received a migration request yet. How did you try to migrate?

**Comment by natgeo-wong** [comment]
Yeap, I will probably test and integrate it into ClimateERA.jl over the course of the next few weeks maybe?

**Comment by michiboo** [comment]
@Balinus  I try to transfer the repo ownership to JuliaClimate but it said that I have no permission to create repo on JuliaClimate

**Comment by juliohm** [comment]
Perhaps you could transfer the repo to some of the members and then they
can transfer to the org.

**Comment by michiboo** [comment]
@Balinus I made a request to transfer the repo to you! 

cc @juliohm

**Comment by Balinus** [comment]
ok, done! I've created a "CDSAPI-team" over at JuliaClimate and invited @michiboo and @juliohm with admin rights over the CDSAPI.jl repo.

Thanks!

**Comment by juliohm** [comment]
Thank you @Balinus for the invitation and for organizing the team :+1:
