### ISSUE TITLE
API for INMET meteorological data (Brazil)

### ISSUE THREAD

**Issue by juliohm** [JuliaClimate/meta#14]
I've finished writing a simple package to retrieve data from meteorological stations in Brazil. The data is public access and I just wrapped the web API into a convenient Julia API: https://github.com/juliohm/INMET.jl

Do you think this package is a good fit for the JuliaClimate organization?

**Comment by juliohm** [comment]
@Balinus @Datseris and others should I register the package in the org or in my personal account?

**Comment by Datseris** [comment]
Sorry for the late reply, I was caught in releasing DynamicalSystems.jl 2.0. 

Personally I have no problem whatsoever to invite the package to the org, it obviously fits! 

On a related note, what I'm not satisfied about, is that we have a lot of small packages each getting data from a single source. I feel this is not really a productive way forwards. We should try to create a single package that can provide data from many sources. But I guess this is more like plan for the future.

**Comment by juliohm** [comment]
I think this goal is unattainable in my opinion. Each data source has its peculiarities and fitting everything to a common API may be challenging. If we have these small packages that are modular, people can load what is necessary for a specific analysis and later on someone can try to load all these packages as dependencies into a major package.

I will migrate the package to the repo, thanks for the quick reply and congrats on DynamicalSystems.jl new release! 🎉

**Comment by Datseris** [comment]
Do you have the necessary privileges to give you ownership level rights for the transfered repo? If not let me know

**Comment by juliohm** [comment]
I think I don't have the privileges to see the settings of the repo, but I am not sure if that is relevant. I will try to push something during the day and will report to you.
